#!/usr/bin/env python
from __future__ import print_function
import sys
from chastesweep import ParamSweeper

if len(sys.argv) < 3:
    print("Parameter names (comma separated) and output file path must be specified:")
    print("chastesweep_genmain param1,param2,param3 MyTemplate.cpp")
    sys.exit(0)

sweeper = ParamSweeper()
sweeper.generate_main_cpp(sys.argv[1].split(","), sys.argv[2])
